version: 2
updates:
  - package-ecosystem: "gradle"
    target-branch: "develop"
    directory: "/"
    labels:
      - "Type: dependencies"
      - "From: bot"
      - "State: verified"
    schedule:
      interval: "daily"